set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

# clock
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

# resetn
set_property PACKAGE_PIN Y3 [get_ports resetn]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]

# uart
set_property PACKAGE_PIN F23 [get_ports uart_rxd]
set_property PACKAGE_PIN H19 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

# ethernet mii
set_property PACKAGE_PIN AB21 [get_ports mii_tx_clk]
set_property PACKAGE_PIN AA19 [get_ports mii_rx_clk]
set_property PACKAGE_PIN AA15 [get_ports mii_tx_en]
set_property PACKAGE_PIN AF18 [get_ports {mii_txd[0]}]
set_property PACKAGE_PIN AE18 [get_ports {mii_txd[1]}]
set_property PACKAGE_PIN W15 [get_ports {mii_txd[2]}]
set_property PACKAGE_PIN W14 [get_ports {mii_txd[3]}]
# set_property PACKAGE_PIN AB20 [get_ports mii_tx_er]
set_property PACKAGE_PIN AE22 [get_ports mii_rx_dv]
set_property PACKAGE_PIN V1 [get_ports {mii_rxd[0]}]
set_property PACKAGE_PIN V4 [get_ports {mii_rxd[1]}]
set_property PACKAGE_PIN V2 [get_ports {mii_rxd[2]}]
set_property PACKAGE_PIN V3 [get_ports {mii_rxd[3]}]
set_property PACKAGE_PIN W16 [get_ports mii_rx_er]
set_property PACKAGE_PIN Y15 [get_ports mii_col]
set_property PACKAGE_PIN AF20 [get_ports mii_crs]
set_property PACKAGE_PIN AE26 [get_ports mii_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports mii_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports mii_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_txd[*]}]
# set_property IOSTANDARD LVCMOS33 [get_ports mii_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports mii_col]
set_property IOSTANDARD LVCMOS33 [get_ports mii_crs]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rst_n]

# ethernet mdio
set_property PACKAGE_PIN W3 [get_ports mdio_mdc]
set_property PACKAGE_PIN W1 [get_ports mdio_mdio_io]

set_property IOSTANDARD LVCMOS33 [get_ports mdio_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_mdio_io]

# usb utmi
create_clock -period 16.667 -name clk -waveform {0.000 8.333} [get_ports utmi_clock_0]
set_property PACKAGE_PIN AF3 [get_ports utmi_chrgvbus_0]
set_property PACKAGE_PIN AA20 [get_ports utmi_clock_0]
set_property PACKAGE_PIN AA3 [get_ports {utmi_data_0[0]}]
set_property PACKAGE_PIN AC3 [get_ports {utmi_data_0[1]}]
set_property PACKAGE_PIN AE1 [get_ports {utmi_data_0[2]}]
set_property PACKAGE_PIN AB4 [get_ports {utmi_data_0[3]}]
set_property PACKAGE_PIN AD3 [get_ports {utmi_data_0[4]}]
set_property PACKAGE_PIN AA4 [get_ports {utmi_data_0[5]}]
set_property PACKAGE_PIN AC4 [get_ports {utmi_data_0[6]}]
set_property PACKAGE_PIN AE2 [get_ports {utmi_data_0[7]}]
set_property PACKAGE_PIN AE3 [get_ports utmi_dischrgvbus_0]
set_property PACKAGE_PIN AC1 [get_ports utmi_dmpulldown_0]
set_property PACKAGE_PIN AC2 [get_ports utmi_dppulldown_0]
set_property PACKAGE_PIN AD4 [get_ports utmi_hostdisc_0]
set_property PACKAGE_PIN W4 [get_ports utmi_iddig_0]
set_property PACKAGE_PIN AD5 [get_ports utmi_idpullup_0]
set_property PACKAGE_PIN AA5 [get_ports {utmi_linestate_0[0]}]
set_property PACKAGE_PIN AE5 [get_ports {utmi_linestate_0[1]}]
set_property PACKAGE_PIN AC6 [get_ports {utmi_opmode_0[0]}]
set_property PACKAGE_PIN AF5 [get_ports {utmi_opmode_0[1]}]
set_property PACKAGE_PIN AD23 [get_ports utmi_reset_0]
set_property PACKAGE_PIN AB5 [get_ports utmi_rxactive_0]
set_property PACKAGE_PIN AB2 [get_ports utmi_rxerror_0]
set_property PACKAGE_PIN AF22 [get_ports utmi_rxvalid_0]
set_property PACKAGE_PIN AF2 [get_ports utmi_sessend_0]
set_property PACKAGE_PIN AE20 [get_ports utmi_suspend_n_0]
set_property PACKAGE_PIN AE21 [get_ports utmi_termsel_0]
set_property PACKAGE_PIN AD21 [get_ports utmi_txready_0]
set_property PACKAGE_PIN AF23 [get_ports utmi_txvalid_0]
set_property PACKAGE_PIN AB1 [get_ports utmi_vbusvalid_0]
set_property PACKAGE_PIN AD20 [get_ports {utmi_xcvrsel_0[0]}]
set_property PACKAGE_PIN AF4 [get_ports {utmi_xcvrsel_0[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports utmi_chrgvbus_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_clock_0]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_dischrgvbus_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_dmpulldown_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_dppulldown_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_hostdisc_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_iddig_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_idpullup_0]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_linestate_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_linestate_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_opmode_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_opmode_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_reset_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_rxactive_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_rxerror_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_rxvalid_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_sessend_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_suspend_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_termsel_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_txready_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_txvalid_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_vbusvalid_0]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_xcvrsel_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_xcvrsel_0[1]}]

