set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

# clock
set_property -dict {PACKAGE_PIN AC19 IOSTANDARD LVCMOS33} [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

# resetn
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD LVCMOS33} [get_ports resetn]

# uart
set_property -dict {PACKAGE_PIN F23 IOSTANDARD LVCMOS33} [get_ports uart_rxd]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33} [get_ports uart_txd]

# ethernet mii
set_property PACKAGE_PIN AB21 [get_ports mii_tx_clk]
set_property PACKAGE_PIN AA19 [get_ports mii_rx_clk]
set_property PACKAGE_PIN AA15 [get_ports mii_tx_en]
set_property PACKAGE_PIN AF18 [get_ports {mii_txd[0]}]
set_property PACKAGE_PIN AE18 [get_ports {mii_txd[1]}]
set_property PACKAGE_PIN W15 [get_ports {mii_txd[2]}]
set_property PACKAGE_PIN W14 [get_ports {mii_txd[3]}]
set_property PACKAGE_PIN AB20 [get_ports mii_tx_er]
set_property PACKAGE_PIN AE22 [get_ports mii_rx_dv]
set_property PACKAGE_PIN V1 [get_ports {mii_rxd[0]}]
set_property PACKAGE_PIN V4 [get_ports {mii_rxd[1]}]
set_property PACKAGE_PIN V2 [get_ports {mii_rxd[2]}]
set_property PACKAGE_PIN V3 [get_ports {mii_rxd[3]}]
set_property PACKAGE_PIN W16 [get_ports mii_rx_er]
set_property PACKAGE_PIN Y15 [get_ports mii_col]
set_property PACKAGE_PIN AF20 [get_ports mii_crs]
set_property PACKAGE_PIN AE26 [get_ports mii_rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports mii_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports mii_tx_en]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_txd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports mii_tx_er]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rx_dv]
set_property IOSTANDARD LVCMOS33 [get_ports {mii_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rx_er]
set_property IOSTANDARD LVCMOS33 [get_ports mii_col]
set_property IOSTANDARD LVCMOS33 [get_ports mii_crs]
set_property IOSTANDARD LVCMOS33 [get_ports mii_rst_n]

# ethernet mdio
set_property -dict {PACKAGE_PIN W3 IOSTANDARD LVCMOS33} [get_ports mdio_mdc]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD LVCMOS33} [get_ports mdio_mdio_io]

# usb utmi
create_clock -period 16.667 -name utmi_clk -waveform {0.000 8.333} [get_ports utmi_clock_0]
set_property PACKAGE_PIN AF3 [get_ports utmi_chrgvbus_0]
set_property PACKAGE_PIN AA20 [get_ports utmi_clock_0]
set_property PACKAGE_PIN AA3 [get_ports {utmi_data_0_tri_io[0]}]
set_property PACKAGE_PIN AC3 [get_ports {utmi_data_0_tri_io[1]}]
set_property PACKAGE_PIN AE1 [get_ports {utmi_data_0_tri_io[2]}]
set_property PACKAGE_PIN AB4 [get_ports {utmi_data_0_tri_io[3]}]
set_property PACKAGE_PIN AD3 [get_ports {utmi_data_0_tri_io[4]}]
set_property PACKAGE_PIN AA4 [get_ports {utmi_data_0_tri_io[5]}]
set_property PACKAGE_PIN AC4 [get_ports {utmi_data_0_tri_io[6]}]
set_property PACKAGE_PIN AE2 [get_ports {utmi_data_0_tri_io[7]}]
set_property PACKAGE_PIN AE3 [get_ports utmi_dischrgvbus_0]
set_property PACKAGE_PIN AC1 [get_ports utmi_dmpulldown_0]
set_property PACKAGE_PIN AC2 [get_ports utmi_dppulldown_0]
set_property PACKAGE_PIN AD4 [get_ports utmi_hostdisc_0]
set_property PACKAGE_PIN W4 [get_ports utmi_iddig_0]
set_property PACKAGE_PIN AD5 [get_ports utmi_idpullup_0]
set_property PACKAGE_PIN AA5 [get_ports {utmi_linestate_0[0]}]
set_property PACKAGE_PIN AE5 [get_ports {utmi_linestate_0[1]}]
set_property PACKAGE_PIN AC6 [get_ports {utmi_opmode_0[0]}]
set_property PACKAGE_PIN AF5 [get_ports {utmi_opmode_0[1]}]
set_property PACKAGE_PIN AD23 [get_ports utmi_reset_0]
set_property PACKAGE_PIN AB5 [get_ports utmi_rxactive_0]
set_property PACKAGE_PIN AB2 [get_ports utmi_rxerror_0]
set_property PACKAGE_PIN AF22 [get_ports utmi_rxvalid_0]
set_property PACKAGE_PIN AF2 [get_ports utmi_sessend_0]
set_property PACKAGE_PIN AE20 [get_ports utmi_suspend_n_0]
set_property PACKAGE_PIN AE21 [get_ports utmi_termsel_0]
set_property PACKAGE_PIN AD21 [get_ports utmi_txready_0]
set_property PACKAGE_PIN AF23 [get_ports utmi_txvalid_0]
set_property PACKAGE_PIN AB1 [get_ports utmi_vbusvalid_0]
set_property PACKAGE_PIN AD20 [get_ports {utmi_xcvrsel_0[0]}]
set_property PACKAGE_PIN AF4 [get_ports {utmi_xcvrsel_0[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports utmi_chrgvbus_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_clock_0]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_data_0_tri_io[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_dischrgvbus_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_dmpulldown_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_dppulldown_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_hostdisc_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_iddig_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_idpullup_0]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_linestate_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_opmode_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_reset_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_rxactive_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_rxerror_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_rxvalid_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_sessend_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_suspend_n_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_termsel_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_txready_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_txvalid_0]
set_property IOSTANDARD LVCMOS33 [get_ports utmi_vbusvalid_0]
set_property IOSTANDARD LVCMOS33 [get_ports {utmi_xcvrsel_0[*]}]

set_output_delay -clock [get_clocks utmi_clk] -min -add_delay 0.000 [get_ports {utmi_data_0_tri_io[*]}]
set_output_delay -clock [get_clocks utmi_clk] -max -add_delay 2.000 [get_ports {utmi_data_0_tri_io[*]}]
set_output_delay -clock [get_clocks utmi_clk] -min -add_delay 0.000 [get_ports utmi_txvalid_0]
set_output_delay -clock [get_clocks utmi_clk] -max -add_delay 2.000 [get_ports utmi_txvalid_0]

# spi flash
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports spi_flash_sck_io]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33} [get_ports {spi_flash_ss_io[0]}]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports spi_flash_io0_io]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports spi_flash_io1_io]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports spi_flash_io2_io]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33} [get_ports spi_flash_io3_io]

# cfg flash
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {cfg_flash_ss_io[0]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVCMOS33} [get_ports cfg_flash_io0_io]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports cfg_flash_io1_io]

# flash timing
set_max_delay 1.5 -from [get_pins -hier *SCK_O_reg_reg/C] -to [get_pins -hier *USRCCLKO] -datapath_only
set_min_delay 0.1 -from [get_pins -hier *SCK_O_reg_reg/C] -to [get_pins -hier *USRCCLKO]
create_generated_clock -name clk_sck -source [get_pins -hierarchical *axi_cfg_spi_0/ext_spi_clk] [get_pins -hierarchical *USRCCLKO] -edges {3 5 7} -edge_shift {7.500 7.500 7.500} 
set_input_delay -clock clk_sck -max 8.100 [get_ports cfg_flash_io*_io] -clock_fall
set_input_delay -clock clk_sck -min 2.450 [get_ports cfg_flash_io*_io] -clock_fall
set_multicycle_path 2 -setup -from clk_sck -to [get_clocks -of_objects [get_pins -hierarchical */ext_spi_clk]]
set_multicycle_path 1 -hold -end -from clk_sck -to [get_clocks -of_objects [get_pins -hierarchical */ext_spi_clk]]
set_output_delay -clock clk_sck -max 3.050 [get_ports cfg_flash_io*_io]
set_output_delay -clock clk_sck -min -2.950 [get_ports cfg_flash_io*_io]
set_multicycle_path 2 -setup -start -from [get_clocks -of_objects [get_pins -hierarchical */ext_spi_clk]] -to clk_sck
set_multicycle_path 1 -hold -from [get_clocks -of_objects [get_pins -hierarchical */ext_spi_clk]] -to clk_sck

# ps/2
set_property -dict {PACKAGE_PIN AD1 IOSTANDARD LVCMOS33} [get_ports ps2_dat_tri_io]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVCMOS33} [get_ports ps2_clk_tri_io]

# led
set_property PACKAGE_PIN K23 [get_ports {led[0]}]
set_property PACKAGE_PIN J21 [get_ports {led[1]}]
set_property PACKAGE_PIN H23 [get_ports {led[2]}]
set_property PACKAGE_PIN J19 [get_ports {led[3]}]
set_property PACKAGE_PIN G9 [get_ports {led[4]}]
set_property PACKAGE_PIN J26 [get_ports {led[5]}]
set_property PACKAGE_PIN J23 [get_ports {led[6]}]
set_property PACKAGE_PIN J8 [get_ports {led[7]}]
set_property PACKAGE_PIN H8 [get_ports {led[8]}]
set_property PACKAGE_PIN G8 [get_ports {led[9]}]
set_property PACKAGE_PIN F7 [get_ports {led[10]}]
set_property PACKAGE_PIN A4 [get_ports {led[11]}]
set_property PACKAGE_PIN A5 [get_ports {led[12]}]
set_property PACKAGE_PIN A3 [get_ports {led[13]}]
set_property PACKAGE_PIN D5 [get_ports {led[14]}]
set_property PACKAGE_PIN H7 [get_ports {led[15]}]
set_property PACKAGE_PIN G7 [get_ports {led_rg0[0]}]
set_property PACKAGE_PIN F8 [get_ports {led_rg0[1]}]
set_property PACKAGE_PIN B5 [get_ports {led_rg1[0]}]
set_property PACKAGE_PIN D6 [get_ports {led_rg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg1[*]}]

# lcd
set_property IOSTANDARD LVCMOS33 [get_ports LCD_*]
set_property PACKAGE_PIN H9 [get_ports {LCD_data_0_tri_io[0]}]
set_property PACKAGE_PIN K17 [get_ports {LCD_data_0_tri_io[1]}]
set_property PACKAGE_PIN J20 [get_ports {LCD_data_0_tri_io[2]}]
set_property PACKAGE_PIN M17 [get_ports {LCD_data_0_tri_io[3]}]
set_property PACKAGE_PIN L17 [get_ports {LCD_data_0_tri_io[4]}]
set_property PACKAGE_PIN L18 [get_ports {LCD_data_0_tri_io[5]}]
set_property PACKAGE_PIN L15 [get_ports {LCD_data_0_tri_io[6]}]
set_property PACKAGE_PIN M15 [get_ports {LCD_data_0_tri_io[7]}]
set_property PACKAGE_PIN M16 [get_ports {LCD_data_0_tri_io[8]}]
set_property PACKAGE_PIN L14 [get_ports {LCD_data_0_tri_io[9]}]
set_property PACKAGE_PIN M14 [get_ports {LCD_data_0_tri_io[10]}]
set_property PACKAGE_PIN F22 [get_ports {LCD_data_0_tri_io[11]}]
set_property PACKAGE_PIN G22 [get_ports {LCD_data_0_tri_io[12]}]
set_property PACKAGE_PIN G21 [get_ports {LCD_data_0_tri_io[13]}]
set_property PACKAGE_PIN H24 [get_ports {LCD_data_0_tri_io[14]}]
set_property PACKAGE_PIN J16 [get_ports {LCD_data_0_tri_io[15]}]
set_property PACKAGE_PIN J25 [get_ports LCD_nrst_0]
set_property PACKAGE_PIN G24 [get_ports LCD_csel_0]
set_property PACKAGE_PIN K8 [get_ports LCD_rd_0]
set_property PACKAGE_PIN K16 [get_ports LCD_rs_0]
set_property PACKAGE_PIN L8 [get_ports LCD_wr_0]
set_property PACKAGE_PIN J15 [get_ports LCD_lighton_0]