set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/utmi_linestate[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/utmi_linestate[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/utmi_opmode[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/utmi_opmode[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/utmi_xcvrsel[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/utmi_xcvrsel[1]}]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_dmpulldown]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_dppulldown]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_rxactive]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_rxerror]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_rxvalid]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_termsel]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_txready]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/utmi_txvalid]


set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/intr]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_araddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_wdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_awaddr[2]}]


set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_araddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_rdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/usbh_host_0/cfg_wdata[11]}]
set_property MARK_DEBUG true [get_nets design_1_i/usbh_host_0/aresetn]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list utmi_clock_0_IBUF]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/usbh_host_0/utmi_opmode[0]} {design_1_i/usbh_host_0/utmi_opmode[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/usbh_host_0/utmi_linestate[0]} {design_1_i/usbh_host_0/utmi_linestate[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 28 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/usbh_host_0/cfg_wdata[0]} {design_1_i/usbh_host_0/cfg_wdata[1]} {design_1_i/usbh_host_0/cfg_wdata[2]} {design_1_i/usbh_host_0/cfg_wdata[3]} {design_1_i/usbh_host_0/cfg_wdata[4]} {design_1_i/usbh_host_0/cfg_wdata[5]} {design_1_i/usbh_host_0/cfg_wdata[6]} {design_1_i/usbh_host_0/cfg_wdata[7]} {design_1_i/usbh_host_0/cfg_wdata[8]} {design_1_i/usbh_host_0/cfg_wdata[9]} {design_1_i/usbh_host_0/cfg_wdata[10]} {design_1_i/usbh_host_0/cfg_wdata[11]} {design_1_i/usbh_host_0/cfg_wdata[12]} {design_1_i/usbh_host_0/cfg_wdata[13]} {design_1_i/usbh_host_0/cfg_wdata[14]} {design_1_i/usbh_host_0/cfg_wdata[15]} {design_1_i/usbh_host_0/cfg_wdata[16]} {design_1_i/usbh_host_0/cfg_wdata[17]} {design_1_i/usbh_host_0/cfg_wdata[18]} {design_1_i/usbh_host_0/cfg_wdata[19]} {design_1_i/usbh_host_0/cfg_wdata[20]} {design_1_i/usbh_host_0/cfg_wdata[21]} {design_1_i/usbh_host_0/cfg_wdata[22]} {design_1_i/usbh_host_0/cfg_wdata[23]} {design_1_i/usbh_host_0/cfg_wdata[28]} {design_1_i/usbh_host_0/cfg_wdata[29]} {design_1_i/usbh_host_0/cfg_wdata[30]} {design_1_i/usbh_host_0/cfg_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/usbh_host_0/cfg_araddr[0]} {design_1_i/usbh_host_0/cfg_araddr[1]} {design_1_i/usbh_host_0/cfg_araddr[2]} {design_1_i/usbh_host_0/cfg_araddr[3]} {design_1_i/usbh_host_0/cfg_araddr[4]} {design_1_i/usbh_host_0/cfg_araddr[5]} {design_1_i/usbh_host_0/cfg_araddr[6]} {design_1_i/usbh_host_0/cfg_araddr[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/usbh_host_0/cfg_awaddr[0]} {design_1_i/usbh_host_0/cfg_awaddr[1]} {design_1_i/usbh_host_0/cfg_awaddr[2]} {design_1_i/usbh_host_0/cfg_awaddr[3]} {design_1_i/usbh_host_0/cfg_awaddr[4]} {design_1_i/usbh_host_0/cfg_awaddr[5]} {design_1_i/usbh_host_0/cfg_awaddr[6]} {design_1_i/usbh_host_0/cfg_awaddr[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/usbh_host_0/cfg_rdata[0]} {design_1_i/usbh_host_0/cfg_rdata[1]} {design_1_i/usbh_host_0/cfg_rdata[2]} {design_1_i/usbh_host_0/cfg_rdata[3]} {design_1_i/usbh_host_0/cfg_rdata[4]} {design_1_i/usbh_host_0/cfg_rdata[5]} {design_1_i/usbh_host_0/cfg_rdata[6]} {design_1_i/usbh_host_0/cfg_rdata[7]} {design_1_i/usbh_host_0/cfg_rdata[8]} {design_1_i/usbh_host_0/cfg_rdata[9]} {design_1_i/usbh_host_0/cfg_rdata[10]} {design_1_i/usbh_host_0/cfg_rdata[11]} {design_1_i/usbh_host_0/cfg_rdata[12]} {design_1_i/usbh_host_0/cfg_rdata[13]} {design_1_i/usbh_host_0/cfg_rdata[14]} {design_1_i/usbh_host_0/cfg_rdata[15]} {design_1_i/usbh_host_0/cfg_rdata[16]} {design_1_i/usbh_host_0/cfg_rdata[17]} {design_1_i/usbh_host_0/cfg_rdata[18]} {design_1_i/usbh_host_0/cfg_rdata[19]} {design_1_i/usbh_host_0/cfg_rdata[20]} {design_1_i/usbh_host_0/cfg_rdata[21]} {design_1_i/usbh_host_0/cfg_rdata[22]} {design_1_i/usbh_host_0/cfg_rdata[23]} {design_1_i/usbh_host_0/cfg_rdata[24]} {design_1_i/usbh_host_0/cfg_rdata[25]} {design_1_i/usbh_host_0/cfg_rdata[26]} {design_1_i/usbh_host_0/cfg_rdata[27]} {design_1_i/usbh_host_0/cfg_rdata[28]} {design_1_i/usbh_host_0/cfg_rdata[29]} {design_1_i/usbh_host_0/cfg_rdata[30]} {design_1_i/usbh_host_0/cfg_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[0]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[1]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[2]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[3]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[4]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[5]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[6]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[7]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[8]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[9]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[10]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[11]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[12]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[13]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[14]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[15]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[16]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[17]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[18]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[19]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[20]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[21]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[22]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[23]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[24]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[25]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[26]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[27]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[28]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[29]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[30]} {design_1_i/usbh_host_0/inst/usb_host_inst/cfg_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/usbh_host_0/utmi_xcvrsel[0]} {design_1_i/usbh_host_0/utmi_xcvrsel[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/usbh_host_0/aresetn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/usbh_host_0/intr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/usbh_host_0/utmi_dmpulldown]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/usbh_host_0/utmi_dppulldown]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/usbh_host_0/utmi_rxactive]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/usbh_host_0/utmi_rxerror]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/usbh_host_0/utmi_rxvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/usbh_host_0/utmi_termsel]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list design_1_i/usbh_host_0/utmi_txready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list design_1_i/usbh_host_0/utmi_txvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets utmi_clock_0_IBUF]
